//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 10:07:59 AM MSK 
//


package by.dziomin.task4WEB.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CallPrices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallPrices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="inCallPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="outCallPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="cityCallPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallPrices", propOrder = {

})
public class CallPrices {

    protected double inCallPrice;
    protected double outCallPrice;
    protected double cityCallPrice;

    /**
     * Gets the value of the inCallPrice property.
     * 
     */
    public double getInCallPrice() {
        return inCallPrice;
    }

    /**
     * Sets the value of the inCallPrice property.
     * 
     */
    public void setInCallPrice(double value) {
        this.inCallPrice = value;
    }

    /**
     * Gets the value of the outCallPrice property.
     * 
     */
    public double getOutCallPrice() {
        return outCallPrice;
    }

    /**
     * Sets the value of the outCallPrice property.
     * 
     */
    public void setOutCallPrice(double value) {
        this.outCallPrice = value;
    }

    /**
     * Gets the value of the cityCallPrice property.
     * 
     */
    public double getCityCallPrice() {
        return cityCallPrice;
    }

    /**
     * Sets the value of the cityCallPrice property.
     * 
     */
    public void setCityCallPrice(double value) {
        this.cityCallPrice = value;
    }

    @Override
    public String toString() {
        return "CallPrices{" +
                "inCallPrice=" + inCallPrice +
                ", outCallPrice=" + outCallPrice +
                ", cityCallPrice=" + cityCallPrice +
                '}';
    }
}
