//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 10:07:59 AM MSK 
//


package by.dziomin.task4WEB.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperatorName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OperatorName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MTS"/>
 *     &lt;enumeration value="A1"/>
 *     &lt;enumeration value="Bilain"/>
 *     &lt;enumeration value="Megaphon"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OperatorName")
@XmlEnum
public enum OperatorName {

    MTS("MTS"),
    @XmlEnumValue("A1")
    A1("A1"),
    @XmlEnumValue("Bilain")
    BILAIN("Bilain"),
    @XmlEnumValue("Megaphon")
    MEGAPHON("Megaphon");
    private final String value;

    OperatorName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OperatorName fromValue(String v) {
        for (OperatorName c: OperatorName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
