//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 10:07:59 AM MSK 
//


package by.dziomin.task4WEB.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Parameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Parameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="favouriteNumber" type="{http://www.epam.training.by/tariffs}FavouriteNumber"/>
 *         &lt;element name="tarification" type="{http://www.epam.training.by/tariffs}Tarification"/>
 *         &lt;element name="startPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Parameters", propOrder = {

})
public class Parameters {

    @XmlElement(defaultValue = "0")
    protected int favouriteNumber;
    @XmlElement(defaultValue = "60")
    protected int tarification;
    protected double startPrice;

    /**
     * Gets the value of the favouriteNumber property.
     * 
     */
    public int getFavouriteNumber() {
        return favouriteNumber;
    }

    /**
     * Sets the value of the favouriteNumber property.
     * 
     */
    public void setFavouriteNumber(int value) {
        this.favouriteNumber = value;
    }

    /**
     * Gets the value of the tarification property.
     * 
     */
    public int getTarification() {
        return tarification;
    }

    /**
     * Sets the value of the tarification property.
     * 
     */
    public void setTarification(int value) {
        this.tarification = value;
    }

    /**
     * Gets the value of the startPrice property.
     * 
     */
    public double getStartPrice() {
        return startPrice;
    }

    /**
     * Sets the value of the startPrice property.
     * 
     */
    public void setStartPrice(double value) {
        this.startPrice = value;
    }

    @Override
    public String toString() {
        return "Parameters{" +
                "favouriteNumber=" + favouriteNumber +
                ", tarification=" + tarification +
                ", startPrice=" + startPrice +
                '}';
    }
}
