//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.27 at 10:07:59 AM MSK 
//


package by.dziomin.task4WEB.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Tarif complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Tarif">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="operatorName" type="{http://www.epam.training.by/tariffs}OperatorName"/>
 *         &lt;element name="payRoll" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="callPrices" type="{http://www.epam.training.by/tariffs}CallPrices"/>
 *         &lt;element name="smsPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="parameters" type="{http://www.epam.training.by/tariffs}Parameters"/>
 *       &lt;/all>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="isActive" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tarif", propOrder = {

})
public class Tarif {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected OperatorName operatorName;
    protected double payRoll;
    @XmlElement(required = true)
    protected CallPrices callPrices = new CallPrices();
    protected double smsPrice;
    @XmlElement(required = true)
    protected Parameters parameters = new Parameters();
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "isActive")
    protected Boolean isActive;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the startDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the operatorName property.
     *
     * @return possible object is
     * {@link OperatorName }
     */
    public OperatorName getOperatorName() {
        return operatorName;
    }

    /**
     * Sets the value of the operatorName property.
     *
     * @param value allowed object is
     *              {@link OperatorName }
     */
    public void setOperatorName(OperatorName value) {
        this.operatorName = value;
    }

    /**
     * Gets the value of the payRoll property.
     */
    public double getPayRoll() {
        return payRoll;
    }

    /**
     * Sets the value of the payRoll property.
     */
    public void setPayRoll(double value) {
        this.payRoll = value;
    }

    /**
     * Gets the value of the callPrices property.
     *
     * @return possible object is
     * {@link CallPrices }
     */
    public CallPrices getCallPrices() {
        return callPrices;
    }

    /**
     * Sets the value of the callPrices property.
     *
     * @param value allowed object is
     *              {@link CallPrices }
     */
    public void setCallPrices(CallPrices value) {
        this.callPrices = value;
    }

    /**
     * Gets the value of the smsPrice property.
     */
    public double getSmsPrice() {
        return smsPrice;
    }

    /**
     * Sets the value of the smsPrice property.
     */
    public void setSmsPrice(double value) {
        this.smsPrice = value;
    }

    /**
     * Gets the value of the parameters property.
     *
     * @return possible object is
     * {@link Parameters }
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     *
     * @param value allowed object is
     *              {@link Parameters }
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isActive property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isIsActive() {
        if (isActive == null) {
            return true;
        } else {
            return isActive;
        }
    }

    /**
     * Sets the value of the isActive property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsActive(Boolean value) {
        this.isActive = value;
    }


    @Override
    public String toString() {
        return "\nTarif{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", startDate=" + startDate +
                ", operatorName=" + operatorName +
                ", payRoll=" + payRoll +
                ", callPrices=" + callPrices +
                ", smsPrice=" + smsPrice +
                ", parameters=" + parameters +
//                ", isActive=" + isActive +
                '}';
    }
}
