CREATE DATABASE IF NOT EXISTS `trade_test` DEFAULT CHARACTER SET utf8 ;

CREATE USER IF NOT EXISTS 'pavel'@'localhost' IDENTIFIED BY 'password';

GRANT SELECT,INSERT,UPDATE,DELETE
ON `trade_test`.*
TO 'pavel'@'localhost';